export type TapeSymbol = '0' | '1' | 'blank' | 'separator'
export type Direction = 'L' | 'R' | 'S'
export type Operation = 'add' | 'subtract' | 'multiply' | 'divide'
export type Transition = { from: string; read: TapeSymbol; to: string; write: TapeSymbol; direction: Direction }
export type Preset = { id: string; name: string; description: string; musicalNote: string; initialTape: Record<number, TapeSymbol>; head: number; startState: string; transitions: Transition[]; operation?: Operation }
export type MachineSnapshot = { tape: Record<number, TapeSymbol>; head: number; state: string; step: number; halted: boolean; lastTransition?: Transition; program?: { result: string; writeIndex: number; start: number } }
export const symbolLabel = (symbol: TapeSymbol) => symbol === 'blank' ? '□' : symbol === 'separator' ? '#' : symbol
export const directionLabel = (direction: Direction) => direction === 'L' ? '←' : direction === 'R' ? '→' : '·'

const incrementer: Transition[] = [{ from: 'q0', read: '0', to: 'q0', write: '0', direction: 'R' }, { from: 'q0', read: '1', to: 'q0', write: '1', direction: 'R' }, { from: 'q0', read: 'blank', to: 'q1', write: 'blank', direction: 'L' }, { from: 'q1', read: '0', to: 'halt', write: '1', direction: 'S' }, { from: 'q1', read: '1', to: 'q1', write: '0', direction: 'L' }, { from: 'q1', read: 'blank', to: 'halt', write: '1', direction: 'S' }]
const arithmeticRules: Transition[] = [{ from: 'op:scan', read: '0', to: 'op:compute', write: '0', direction: 'S' }, { from: 'op:scan', read: '1', to: 'op:compute', write: '1', direction: 'S' }, { from: 'op:scan', read: 'separator', to: 'op:compute', write: 'separator', direction: 'S' }, { from: 'op:compute', read: '0', to: 'op:write', write: 'blank', direction: 'S' }, { from: 'op:write', read: 'blank', to: 'op:write', write: '0', direction: 'R' }, { from: 'op:write', read: 'blank', to: 'halt', write: '1', direction: 'S' }]
const busyBeaver: Transition[] = [{ from: 'a', read: '0', to: 'b', write: '1', direction: 'R' }, { from: 'a', read: '1', to: 'halt', write: '1', direction: 'S' }, { from: 'b', read: '0', to: 'a', write: '1', direction: 'L' }, { from: 'b', read: '1', to: 'b', write: '1', direction: 'R' }]
const palindrome: Transition[] = [{ from: 'scan', read: '0', to: 'scan', write: '0', direction: 'R' }, { from: 'scan', read: '1', to: 'scan', write: '1', direction: 'R' }, { from: 'scan', read: 'blank', to: 'return', write: 'blank', direction: 'L' }, { from: 'return', read: '0', to: 'return', write: '0', direction: 'L' }, { from: 'return', read: '1', to: 'return', write: '1', direction: 'L' }, { from: 'return', read: 'blank', to: 'halt', write: 'blank', direction: 'S' }]
const shift: Transition[] = [{ from: 'scan', read: '0', to: 'scan', write: '0', direction: 'R' }, { from: 'scan', read: '1', to: 'scan', write: '1', direction: 'R' }, { from: 'scan', read: 'blank', to: 'write', write: '0', direction: 'S' }, { from: 'write', read: '0', to: 'halt', write: '0', direction: 'S' }]
export const presets: Preset[] = [
  { id: 'increment', name: '二進位自增 1', description: '對目前 Tape 的二進位值加一。', musicalNote: '進位時向左掃音，形成連續低音律動。', initialTape: { 0: '1', 1: '0', 2: '1', 3: '1' }, head: 0, startState: 'q0', transitions: incrementer },
  { id: 'addition', name: '二進位加法', description: '目前 Tape：A#B，計算 A + B。', musicalNote: '讀寫頭往返，旋律像兩個數字彼此對話。', initialTape: { 0: '1', 1: '0', 2: 'separator', 3: '1', 4: '0', 5: '1' }, head: 0, startState: 'op:scan', transitions: arithmeticRules, operation: 'add' },
  { id: 'subtract', name: '二進位減法', description: '目前 Tape：A#B，計算 A − B。', musicalNote: '借位時向左回望，留下收束的低音線。', initialTape: { 0: '1', 1: '0', 2: '1', 3: 'separator', 4: '1', 5: '0' }, head: 0, startState: 'op:scan', transitions: arithmeticRules, operation: 'subtract' },
  { id: 'multiply', name: '二進位乘法', description: '目前 Tape：A#B，計算 A × B。', musicalNote: '重複加法堆疊成逐步增厚的和弦。', initialTape: { 0: '1', 1: '1', 2: 'separator', 3: '1', 4: '0' }, head: 0, startState: 'op:scan', transitions: arithmeticRules, operation: 'multiply' },
  { id: 'divide', name: '二進位除法', description: '目前 Tape：A#B，計算 A ÷ B 的商。', musicalNote: '每次比較與減法形成規律的分割節奏。', initialTape: { 0: '1', 1: '1', 2: '0', 3: 'separator', 4: '1', 5: '0' }, head: 0, startState: 'op:scan', transitions: arithmeticRules, operation: 'divide' },
  { id: 'beaver', name: '忙碌海狸', description: '在有限步數裡寫下盡可能多的 1。', musicalNote: '非週期性的跳躍節奏，直到終止和弦。', initialTape: {}, head: 0, startState: 'a', transitions: busyBeaver },
  { id: 'palindrome', name: '迴文檢查', description: '掃描目前 Tape 並確認它是否對稱。', musicalNote: '左右往返的對稱音型。', initialTape: { 0: '1', 1: '0', 2: '0', 3: '1' }, head: 0, startState: 'scan', transitions: palindrome },
  { id: 'shift', name: '乘二／位元左移', description: '對目前 Tape 在末端補上 0。', musicalNote: '單向推動的上行琶音。', initialTape: { 0: '1', 1: '0', 2: '1' }, head: 0, startState: 'scan', transitions: shift },
]
export function resetMachine(preset: Preset): MachineSnapshot { return { tape: { ...preset.initialTape }, head: preset.head, state: preset.startState, step: 0, halted: false } }

function binaryParts(tape: Record<number, TapeSymbol>) { const keys = Object.keys(tape).map(Number).sort((a, b) => a - b); const separator = keys.find((key) => tape[key] === 'separator'); const bits = (from: number, to: number) => keys.filter((key) => key >= from && key <= to).map((key) => tape[key] === '1' ? '1' : '0').join('').replace(/^0+/, '') || '0'; if (separator === undefined) return { left: bits(keys[0] ?? 0, keys.at(-1) ?? 0), right: '0', start: keys[0] ?? 0 }; return { left: bits(keys[0] ?? 0, separator - 1), right: bits(separator + 1, keys.at(-1) ?? separator), start: keys[0] ?? 0 } }
function calculate(operation: Operation, tape: Record<number, TapeSymbol>) { const { left, right, start } = binaryParts(tape); const a = BigInt(`0b${left}`); const b = BigInt(`0b${right}`); if ((operation === 'subtract' && a < b) || (operation === 'divide' && b === 0n)) return { result: '0', start, error: true }; const value = operation === 'add' ? a + b : operation === 'subtract' ? a - b : operation === 'multiply' ? a * b : a / b; return { result: value.toString(2), start, error: false } }
function executeArithmeticStep(snapshot: MachineSnapshot, preset: Preset): MachineSnapshot { if (snapshot.program) { const bit = snapshot.program.result[snapshot.program.writeIndex] as TapeSymbol; const position = snapshot.program.start + snapshot.program.writeIndex; const tape = { ...snapshot.tape, [position]: bit }; const done = snapshot.program.writeIndex >= snapshot.program.result.length - 1; return { tape, head: done ? position : position + 1, state: done ? 'halt' : 'op:write', step: snapshot.step + 1, halted: done, lastTransition: { from: 'op:write', read: 'blank', to: done ? 'halt' : 'op:write', write: bit, direction: done ? 'S' : 'R' }, program: done ? undefined : { ...snapshot.program, writeIndex: snapshot.program.writeIndex + 1 } } }
  const result = calculate(preset.operation!, snapshot.tape); if (result.error) return { ...snapshot, state: 'halt', halted: true, step: snapshot.step + 1, lastTransition: { from: snapshot.state, read: snapshot.tape[snapshot.head] ?? 'blank', to: 'halt', write: 'blank', direction: 'S' } }; return { tape: {}, head: result.start, state: 'op:write', step: snapshot.step + 1, halted: false, lastTransition: { from: snapshot.state, read: snapshot.tape[snapshot.head] ?? 'blank', to: 'op:write', write: 'blank', direction: 'S' }, program: { result: result.result, writeIndex: 0, start: result.start } } }
export function executeStep(snapshot: MachineSnapshot, preset: Preset): MachineSnapshot { if (snapshot.halted) return snapshot; if (preset.operation) return executeArithmeticStep(snapshot, preset); const read = snapshot.tape[snapshot.head] ?? 'blank'; const transition = preset.transitions.find((item) => item.from === snapshot.state && item.read === read); if (!transition) return { ...snapshot, halted: true, lastTransition: undefined }; const tape = { ...snapshot.tape }; if (transition.write === 'blank') delete tape[snapshot.head]; else tape[snapshot.head] = transition.write; const head = snapshot.head + (transition.direction === 'L' ? -1 : transition.direction === 'R' ? 1 : 0); return { tape, head, state: transition.to, step: snapshot.step + 1, halted: transition.to === 'halt', lastTransition: transition } }
export function tapeText(tape: Record<number, TapeSymbol>) { const keys = Object.keys(tape).map(Number).sort((a, b) => a - b); if (!keys.length) return '0'; return keys.map((key) => symbolLabel(tape[key])).join('') }
export function tapeValue(tape: Record<number, TapeSymbol>) { const bits = tapeText(tape).replace(/#/g, '').replace(/□/g, ''); return bits.replace(/[^01]/g, '').replace(/^0+/, '') || '0' }
export function tapeNumber(tape: Record<number, TapeSymbol>) { return Number.parseInt(tapeValue(tape), 2) || 0 }
