import { useCallback, useEffect, useMemo, useState } from 'react'
import { directionLabel, executeStep, presets, resetMachine, symbolLabel, tapeValue, type MachineSnapshot, type Preset, type TapeSymbol } from './core/turing'
import { pianoFrequency, playTone } from './core/audio'
import './App.css'

const keyNames = ['F','F♯','G','G♯','A','A♯','B','C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B','C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B','C','C♯','D','D♯','E','F']
const blackKeys = new Set(['F♯','G♯','A♯','C♯','D♯'])
const whiteKeyIndices = keyNames.map((name, index) => blackKeys.has(name) ? -1 : index).filter((index) => index >= 0)
const whitePurposes = ['STATE 0','STATE 1','STATE 2','STATE 3','STATE 4','STATE 5','HALT','READ 0','READ 1','MOVE LEFT','MOVE RIGHT','WRITE 0','WRITE 1','BLANK','STEP','CARRY','COMPARE','STATE CHANGE','FINAL CHORD','RESERVED','RESERVED','RESERVED']
const whiteKeyboardMap = ['z','x','c','v','b','n','m','q','w','e','r','t','y','u','i','o','p','a','s','d','f','g']
const keyboardMap = keyNames.map((_, index) => whiteKeyboardMap[whiteKeyIndices.indexOf(index)] ?? '—')
const keyPurpose = (index: number) => { const whiteIndex = whiteKeyIndices.indexOf(index); return whiteIndex >= 0 ? whitePurposes[whiteIndex] : 'MELODY ONLY' }

function App() {
  const [preset, setPreset] = useState<Preset>(presets[0]); const [machine, setMachine] = useState<MachineSnapshot>(() => resetMachine(presets[0])); const [running, setRunning] = useState(false); const [speed, setSpeed] = useState(4); const [mode, setMode] = useState<'auto'|'manual'>('auto'); const [pressedKey, setPressedKey] = useState<number|null>(null)
  const reset = useCallback((next = preset) => { setRunning(false); setMachine((current) => ({ ...current, state: next.startState, step: 0, halted: false, lastTransition: undefined })) }, [preset])
  const step = useCallback(() => { setMachine((current) => { const next = executeStep(current, preset); const rule = next.lastTransition; if (rule) { const midi = rule.direction === 'L' ? 48 : rule.direction === 'R' ? 60 : rule.write === '1' ? 67 : 64; playTone(pianoFrequency(midi), .2, rule.to === 'halt' ? 'sine' : 'triangle') } else playTone(pianoFrequency(41), .5, 'sine'); if (next.halted) setRunning(false); return next }) }, [preset])
  const activateKey = useCallback((index: number) => {
    setPressedKey(index); playTone(pianoFrequency(41 + index), .45); window.setTimeout(() => setPressedKey(null), 220)
    const action = keyPurpose(index)
    if (!action) return
    if (action === 'STEP') { step(); return }
    setMachine((current) => {
      const tape = { ...current.tape }
      if (action === 'MOVE LEFT') return { ...current, head: current.head - 1, step: current.step + 1 }
      if (action === 'MOVE RIGHT') return { ...current, head: current.head + 1, step: current.step + 1 }
      if (action === 'WRITE 0') { tape[current.head] = '0'; return { ...current, tape, step: current.step + 1 } }
      if (action === 'WRITE 1') { tape[current.head] = '1'; return { ...current, tape, step: current.step + 1 } }
      if (action === 'BLANK') { delete tape[current.head]; return { ...current, tape, step: current.step + 1 } }
      return current
    })
  }, [step])
  useEffect(() => { if (!running || machine.halted) return; const timer = window.setInterval(step, 1000 / speed); return () => window.clearInterval(timer) }, [running, machine.halted, speed, step])
  useEffect(() => { const onKey = (event: KeyboardEvent) => { const pianoIndex = keyboardMap.indexOf(event.key.toLowerCase()); if (pianoIndex >= 0) { if (!event.repeat) activateKey(pianoIndex); return }; if (event.code === 'Space') { event.preventDefault(); setRunning((value) => !value) }; if (event.shiftKey && event.key.toLowerCase() === 's') step(); if (event.shiftKey && event.key.toLowerCase() === 'r') reset() }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [activateKey, reset, step])
  const cells = useMemo(() => Array.from({ length: 13 }, (_, index) => machine.head - 6 + index), [machine.head]); const activeRule = machine.lastTransition; const displayState = machine.halted ? 'HALT' : machine.state.toUpperCase()
  const choosePreset = (next: Preset) => { setPreset(next); setRunning(false); setMachine((current) => ({ ...current, state: next.startState, step: 0, halted: false, lastTransition: undefined })) }; const editCell = (position: number) => setMachine((current) => { const currentSymbol = current.tape[position] ?? 'blank'; const nextSymbol: TapeSymbol = currentSymbol === 'blank' ? '0' : currentSymbol === '0' ? '1' : 'blank'; const tape = { ...current.tape }; if (nextSymbol === 'blank') delete tape[position]; else tape[position] = nextSymbol; return { ...current, tape } })
  return <main className="app-shell">
    <header className="masthead"><div className="brand-mark"><span>PTM</span><i /></div><div><p className="eyebrow">A MUSICAL COMPUTATION INSTRUMENT</p><h1>Piano <em>Turing</em> Machine</h1></div><div className="machine-status"><span className={running ? 'status-dot live' : 'status-dot'} />{running ? 'COMPUTING' : machine.halted ? 'HALTED' : 'READY'}</div></header>
    <section className="tape-panel panel-texture"><div className="section-label"><span>01 / TAPE READER</span><span>DOUBLE-SIDED · READ / WRITE</span></div><div className="tape-window"><div className="tape-cells">{cells.map((position) => <button className={`tape-cell ${position === machine.head ? 'selected' : ''}`} key={position} onClick={() => editCell(position)}><span className="position">{position}</span><strong>{symbolLabel(machine.tape[position] ?? 'blank')}</strong>{position === machine.head && <span className="needle">⌄</span>}</button>)}</div></div><div className="tape-caption"><span>◉ HEAD POSITION <b>{machine.head >= 0 ? '+' : ''}{machine.head}</b></span><span>SYMBOL <b>{symbolLabel(machine.tape[machine.head] ?? 'blank')}</b></span><span>VALUE <b>{tapeValue(machine.tape)}<small>₁₀</small></b></span></div></section>
    <section className="piano-panel"><div className="section-label"><span>02 / THE INSTRUMENT</span><span>F2 — F5 · 37 KEYS</span></div><div className="piano-wrap"><div className="piano"><div className="keybed">{keyNames.map((name, index) => { const active = pressedKey === index || Boolean(activeRule && ((activeRule.direction === 'L' && index === 2) || (activeRule.direction === 'R' && index === 29))); return <button key={`${name}-${index}`} title={`${name}${index % 12 === 0 ? Math.floor(index / 12 + 2) : ''} — ${keyPurpose(index)} — keyboard ${keyboardMap[index]}`} aria-label={`${name} — ${keyPurpose(index)} — keyboard ${keyboardMap[index]}`} className={`piano-key ${blackKeys.has(name) ? 'black' : 'white'} ${active ? 'active' : ''}`} onClick={() => { setPressedKey(index); playTone(pianoFrequency(41 + index), .45); window.setTimeout(() => setPressedKey(null), 220) }}><span>{index % 12 === 0 ? name + Math.floor(index / 12 + 2) : name}</span></button> })}</div></div><div className="hand-labels"><span>LEFT HAND · STATE / STRUCTURE</span><span>RIGHT HAND · TAPE / MOTION</span></div></div><div className="piano-legend"><span><i className="legend-dot bass" />STATE TRANSITION</span><span><i className="legend-dot melody" />TAPE ACTION</span><span className="small-note">Hover a key for its calculation</span></div><div className="how-to"><strong>HOW TO PLAY</strong><span><b>1</b> 選右側範例　<b>2</b> 點擊 Tape 格子循環 □ → 0 → 1　<b>3</b> 按 PLAY 自動演算</span><span><b>⌨</b> 下排 <kbd>Z S X D C V G B H N J M</kbd> State　上排 <kbd>Q 2 W 3 E 4 R 5 T 6 Y 7 U 8 I 9 O 0 P - [ = ] \</kbd> Action　<b>SPACE</b> 播放　<b>Shift+S</b> 單步　<b>Shift+R</b> 重置</span></div><details className="key-map"><summary>KEY MAP — 每個按鍵的計算用途</summary><div className="key-map-grid">{keyNames.map((name, index) => <span key={`map-${name}-${index}`}><b>{keyboardMap[index]}</b>{name}{index % 12 === 0 ? Math.floor(index / 12 + 2) : ''} · {keyPurpose(index)}</span>)}</div></details></section>
    <section className="control-grid"><div className="controls panel-texture"><div className="section-label"><span>03 / TRANSPORT</span><span>SPACE TO PLAY</span></div><div className="transport"><button className="play-button" onClick={() => setRunning((value) => !value)}>{running ? 'Ⅱ' : '▶'}</button><button onClick={step}>STEP <kbd>S</kbd></button><button onClick={() => reset()}>RESET <kbd>R</kbd></button></div><label className="range-label">TEMPO <strong>{speed} steps / sec</strong><input type="range" min="1" max="12" value={speed} onChange={(event) => setSpeed(Number(event.target.value))} /></label><div className="mode-toggle"><button className={mode === 'auto' ? 'selected' : ''} onClick={() => setMode('auto')}>AUTO COMPUTE</button><button className={mode === 'manual' ? 'selected' : ''} onClick={() => setMode('manual')}>EXPLORE</button></div></div><div className="readout"><div className="section-label"><span>04 / MACHINE STATE</span><span>LIVE TELEMETRY</span></div><div className="readout-main"><div><span className="readout-label">CURRENT STATE</span><strong>{displayState}</strong></div><div><span className="readout-label">STEP COUNT</span><strong>{String(machine.step).padStart(3, '0')}</strong></div><div><span className="readout-label">INPUT SYMBOL</span><strong>{symbolLabel(machine.tape[machine.head] ?? 'blank')}</strong></div></div><p className="status-message">{machine.halted ? 'The machine has reached its terminal state. A final chord marks the end.' : activeRule ? `Rule fired: ${activeRule.from} reads ${symbolLabel(activeRule.read)} and writes ${symbolLabel(activeRule.write)}.` : 'Awaiting the first instruction.'}</p></div></section>
    <section className="lower-grid"><div className="preset-panel"><div className="section-label"><span>05 / REPERTOIRE</span><span>SELECT A PROGRAM</span></div><div className="preset-list">{presets.map((item, index) => <button className={`preset ${item.id === preset.id ? 'selected' : ''}`} key={item.id} onClick={() => choosePreset(item)}><span className="preset-number">0{index + 1}</span><span><strong>{item.name}</strong><small>{item.description}</small></span><span className="arrow">↗</span></button>)}</div></div><div className="rules-panel"><div className="section-label"><span>06 / TRANSITION TABLE</span><span>δ(Q, Σ) → (Q′, Σ′, D)</span></div><div className="table-wrap"><table><thead><tr><th>FROM</th><th>READ</th><th>WRITE</th><th>MOVE</th><th>TO</th></tr></thead><tbody>{preset.transitions.map((rule, index) => <tr className={activeRule === rule ? 'fired' : ''} key={`${rule.from}-${rule.read}-${index}`}><td>{rule.from}</td><td>{symbolLabel(rule.read)}</td><td>{symbolLabel(rule.write)}</td><td>{directionLabel(rule.direction)}</td><td>{rule.to}</td></tr>)}</tbody></table></div></div></section>
    <footer><span>PIANO TURING MACHINE / 2026</span><span>{preset.musicalNote}</span><span>AN INSTRUMENT FOR THINKING</span></footer>
  </main>
}
export default App
