import { useCallback, useEffect, useMemo, useState } from 'react'
import { directionLabel, executeStep, inputTape, presets, resetMachine, symbolLabel, tapeInput, tapeNumber, tapeText, tapeValue, type MachineSnapshot, type Preset, type TapeSymbol } from './core/turing'
import { parseOperationInput, type OperationId } from './core/operations'
import { pianoFrequency, playTone } from './core/audio'
import './App.css'

const keyNames = ['F','F♯','G','G♯','A','A♯','B','C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B','C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B','C','C♯','D','D♯','E','F']
const blackKeys = new Set(['F♯','G♯','A♯','C♯','D♯'])
const whiteKeyIndices = keyNames.map((name, index) => blackKeys.has(name) ? -1 : index).filter((index) => index >= 0)
const whitePurposes = ['STATE 0','STATE 1','STATE 2','STATE 3','STATE 4','STATE 5','HALT','READ 0','READ 1','MOVE LEFT','MOVE RIGHT','WRITE 0','WRITE 1','BLANK','STEP','CARRY','COMPARE','STATE CHANGE','FINAL CHORD','RESERVED','RESERVED','RESERVED']
const whiteKeyboardMap = ['z','x','c','v','b','n','m','q','w','e','r','t','y','u','i','o','p','a','s','d','f','g']
const keyboardMap = keyNames.map((_, index) => whiteKeyboardMap[whiteKeyIndices.indexOf(index)] ?? '—')
const keyPurpose = (index: number) => { const whiteIndex = whiteKeyIndices.indexOf(index); return whiteIndex >= 0 ? whitePurposes[whiteIndex] : 'MELODY ONLY' }
const transitionPurposes = (rule: MachineSnapshot['lastTransition']) => {
  if (!rule) return []
  const purposes: string[] = []
  if (rule.read !== 'blank') purposes.push(`READ ${rule.read}`)
  purposes.push(rule.write === 'blank' ? 'BLANK' : `WRITE ${rule.write}`)
  if (rule.direction === 'L') purposes.push('MOVE LEFT')
  if (rule.direction === 'R') purposes.push('MOVE RIGHT')
  if (rule.to === 'halt') purposes.push('HALT')
  else { const stateNumber = rule.to.match(/\d+/)?.[0]; if (stateNumber) purposes.push(`STATE ${stateNumber}`) }
  return purposes
}
const operationForPreset = (item: Preset): OperationId => item.operation ?? item.id as OperationId
const operationLabel = (operation: OperationId) => ({ increment: '加一', shift: '左移', add: '加法', subtract: '減法', multiply: '乘法', divide: '除法', palindrome: '迴文檢查' }[operation])

function App() {
  const [preset, setPreset] = useState<Preset>(presets[0]); const [machine, setMachine] = useState<MachineSnapshot>(() => resetMachine(presets[0])); const [running, setRunning] = useState(false); const [speed, setSpeed] = useState(4); const [mode, setMode] = useState<'auto'|'manual'>('auto'); const [pressedKey, setPressedKey] = useState<number|null>(null); const [inputDraft, setInputDraft] = useState(() => tapeInput(presets[0].initialTape));
  const reset = useCallback((next = preset) => { setRunning(false); setMachine((current) => ({ ...current, state: next.startState, step: 0, halted: false, lastTransition: undefined, program: undefined })) }, [preset])
  const step = useCallback(() => { setMachine((current) => { const next = executeStep(current, preset); const rule = next.lastTransition; if (rule) { const midi = rule.direction === 'L' ? 48 : rule.direction === 'R' ? 60 : rule.write === '1' ? 67 : 64; playTone(pianoFrequency(midi), .2, rule.to === 'halt' ? 'sine' : 'triangle') } else playTone(pianoFrequency(41), .5, 'sine'); if (next.halted) setRunning(false); return next }) }, [preset])
  const activateKey = useCallback((index: number) => {
    setPressedKey(index); playTone(pianoFrequency(41 + index), .45); window.setTimeout(() => setPressedKey(null), 220)
    const action = keyPurpose(index)
    if (!action) return
    if (action === 'STEP') { step(); return }
    setMachine((current) => {
      const tape = { ...current.tape }
      if (action === 'MOVE LEFT') return { ...current, head: current.head - 1, step: current.step + 1 }
      if (action === 'MOVE RIGHT') return { ...current, head: current.head + 1, step: current.step + 1 }
      if (action === 'WRITE 0') { tape[current.head] = '0'; setInputDraft(tapeInput(tape)); return { ...current, tape, step: current.step + 1 } }
      if (action === 'WRITE 1') { tape[current.head] = '1'; setInputDraft(tapeInput(tape)); return { ...current, tape, step: current.step + 1 } }
      if (action === 'BLANK') { delete tape[current.head]; setInputDraft(tapeInput(tape)); return { ...current, tape, step: current.step + 1 } }
      return current
    })
  }, [step])
  useEffect(() => { if (!running || machine.halted) return; const timer = window.setInterval(step, 1000 / speed); return () => window.clearInterval(timer) }, [running, machine.halted, speed, step])
  useEffect(() => { const onKey = (event: KeyboardEvent) => { const pianoIndex = keyboardMap.indexOf(event.key.toLowerCase()); if (pianoIndex >= 0) { if (!event.repeat) activateKey(pianoIndex); return }; if (event.code === 'Space') { event.preventDefault(); setRunning((value) => !value) }; if (event.shiftKey && event.key.toLowerCase() === 's') step(); if (event.shiftKey && event.key.toLowerCase() === 'r') reset() }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [activateKey, reset, step])
  const cells = useMemo(() => Array.from({ length: 13 }, (_, index) => machine.head - 6 + index), [machine.head]); const activeRule = machine.lastTransition; const activePurposes = running && !machine.halted ? transitionPurposes(activeRule) : []; const displayState = machine.halted ? 'HALT' : machine.state.toUpperCase(); const operation = operationForPreset(preset); const validation = parseOperationInput(operation, inputDraft); const operands = inputDraft.split('#');
  const applyInput = (nextInput: string) => { setInputDraft(nextInput); setRunning(false); setMachine((current) => ({ ...current, tape: inputTape(nextInput), head: 0, state: preset.startState, step: 0, halted: false, lastTransition: undefined, program: undefined })) }
  const choosePreset = (next: Preset) => { setPreset(next); setRunning(false); setMachine((current) => ({ ...current, state: next.startState, step: 0, halted: false, lastTransition: undefined, program: undefined })) }; const loadExample = () => { setRunning(false); setMachine(resetMachine(preset)); setInputDraft(tapeInput(preset.initialTape)) }; const editCell = (position: number) => setMachine((current) => { const currentSymbol = current.tape[position] ?? 'blank'; const nextSymbol: TapeSymbol = currentSymbol === 'blank' ? '0' : currentSymbol === '0' ? '1' : currentSymbol === '1' ? 'separator' : 'blank'; const tape = { ...current.tape }; if (nextSymbol === 'blank') delete tape[position]; else tape[position] = nextSymbol; setInputDraft(tapeInput(tape)); return { ...current, tape, halted: false, program: undefined } })
  const togglePlay = () => { if (!running && !validation.ok) { setRunning(false); return } setRunning((value) => !value) }
  return <main className="app-shell">
    <header className="masthead"><div className="brand-mark"><span>PTM</span><i /></div><div><p className="eyebrow">A MUSICAL COMPUTATION INSTRUMENT</p><h1>Piano <em>Turing</em> Machine</h1></div><div className="machine-status"><span className={running ? 'status-dot live' : 'status-dot'} />{running ? 'COMPUTING' : machine.halted ? 'HALTED' : 'READY'}</div></header>
    <section className="tape-panel panel-texture"><div className="section-label"><span>01 / TAPE READER</span><span>DOUBLE-SIDED · READ / WRITE</span></div><div className="tape-window"><div className="tape-cells">{cells.map((position) => <button className={`tape-cell ${position === machine.head ? 'selected' : ''}`} key={position} onClick={() => editCell(position)}><span className="position">{position}</span><strong>{symbolLabel(machine.tape[position] ?? 'blank')}</strong>{position === machine.head && <span className="needle">⌄</span>}</button>)}</div></div><div className="tape-caption"><span>◉ HEAD POSITION <b>{machine.head >= 0 ? '+' : ''}{machine.head}</b></span><span>SYMBOL <b>{symbolLabel(machine.tape[machine.head] ?? 'blank')}</b></span><span>VALUE <b>{tapeNumber(machine.tape).toString(8)}<small>₈</small></b><small className="value-breakdown">TAPE {tapeText(machine.tape)} · BIN {tapeValue(machine.tape)} · DEC {tapeNumber(machine.tape)}</small></span></div></section>
    <section className="piano-panel"><div className="section-label"><span>02 / THE INSTRUMENT</span><span>F2 — F5 · 37 KEYS</span></div><div className="piano-wrap"><div className="piano"><div className="keybed">{keyNames.map((name, index) => { const active = pressedKey === index || activePurposes.includes(keyPurpose(index)); return <button key={`${name}-${index}`} title={`${name}${index % 12 === 0 ? Math.floor(index / 12 + 2) : ''} — ${keyPurpose(index)} — keyboard ${keyboardMap[index]}`} aria-label={`${name} — ${keyPurpose(index)} — keyboard ${keyboardMap[index]}`} className={`piano-key ${blackKeys.has(name) ? 'black' : 'white'} ${active ? 'active' : ''}`} onClick={() => activateKey(index)}><span>{index % 12 === 0 ? name + Math.floor(index / 12 + 2) : name}</span></button> })}</div></div><div className="hand-labels"><span>LEFT HAND · STATE / STRUCTURE</span><span>RIGHT HAND · TAPE / MOTION</span></div></div><div className="piano-legend"><span><i className="legend-dot bass" />STATE TRANSITION</span><span><i className="legend-dot melody" />TAPE ACTION</span><span className="small-note">Hover a key for its calculation</span></div><div className="how-to"><strong>HOW TO PLAY</strong><span><b>1</b> 選右側範例　<b>2</b> 點擊 Tape 格子循環 □ → 0 → 1　<b>3</b> 按 PLAY 自動演算</span><span><b>⌨</b> 下排 <kbd>Z S X D C V G B H N J M</kbd> State　上排 <kbd>Q 2 W 3 E 4 R 5 T 6 Y 7 U 8 I 9 O 0 P - [ = ] \</kbd> Action　<b>SPACE</b> 播放　<b>Shift+S</b> 單步　<b>Shift+R</b> 重置</span></div><details className="key-map"><summary>KEY MAP — 每個按鍵的計算用途</summary><div className="key-map-grid">{keyNames.map((name, index) => <span key={`map-${name}-${index}`}><b>{keyboardMap[index]}</b>{name}{index % 12 === 0 ? Math.floor(index / 12 + 2) : ''} · {keyPurpose(index)}</span>)}</div></details></section>
    <section className="control-grid"><div className="controls panel-texture"><div className="section-label"><span>03 / TRANSPORT</span><span>PLAY CURRENT TAPE</span></div><div className="transport"><button className="play-button" onClick={togglePlay}>{running ? 'Ⅱ' : '▶'}</button><button onClick={step}>STEP <kbd>S</kbd></button><button onClick={() => reset()}>RESET STATE <kbd>R</kbd></button></div><label className="range-label">TEMPO <strong>{speed} steps / sec</strong><input type="range" min="1" max="12" value={speed} onChange={(event) => setSpeed(Number(event.target.value))} /></label><div className="mode-toggle"><button className={mode === 'auto' ? 'selected' : ''} onClick={() => setMode('auto')}>AUTO COMPUTE</button><button className={mode === 'manual' ? 'selected' : ''} onClick={() => setMode('manual')}>EXPLORE</button></div></div><div className="readout"><div className="section-label"><span>04 / MACHINE STATE</span><span>LIVE TELEMETRY</span></div><div className="readout-main"><div><span className="readout-label">CURRENT STATE</span><strong>{displayState}</strong></div><div><span className="readout-label">STEP COUNT</span><strong>{String(machine.step).padStart(3, '0')}</strong></div><div><span className="readout-label">INPUT SYMBOL</span><strong>{symbolLabel(machine.tape[machine.head] ?? 'blank')}</strong></div></div><p className="status-message">{!validation.ok ? validation.error.message : machine.halted ? '完成。Tape 已留下結果，可按 RUN AGAIN 重跑。' : activeRule ? `Current rule: ${activeRule.from} reads ${symbolLabel(activeRule.read)}, writes ${symbolLabel(activeRule.write)}, then ${directionLabel(activeRule.direction)}.` : 'Ready：PLAY 會執行目前的 Tape，不會載入範例。'}</p></div></section>
    <section className="operation-workspace"><div className="operation-editor"><div className="section-label"><span>05 / OPERATION</span><span>{operationLabel(operation)} · {operation}</span></div><div className="operation-fields">{operands.slice(0, operation === 'add' || operation === 'subtract' || operation === 'multiply' || operation === 'divide' ? 2 : 1).map((value, index) => <label key={index}>{operation === 'add' || operation === 'subtract' || operation === 'multiply' || operation === 'divide' ? index === 0 ? 'A' : 'B' : 'VALUE'}<input value={value} onChange={(event) => { const next = [...operands]; next[index] = event.target.value; applyInput(next.slice(0, 2).join(operation === 'add' || operation === 'subtract' || operation === 'multiply' || operation === 'divide' ? '#' : '')) }} /></label>)}</div><div className="operation-preview"><span>INPUT FORMAT</span><strong>{operation === 'add' || operation === 'subtract' || operation === 'multiply' || operation === 'divide' ? 'A#B' : 'A'}</strong><span>PREVIEW</span><b>{validation.ok ? validation.input : inputDraft || '—'}</b>{!validation.ok && <em>{validation.error.code}</em>}</div><div className="operation-actions"><button onClick={loadExample}>LOAD EXAMPLE</button><button onClick={() => reset()}>RESET STATE</button><button className="primary-action" onClick={togglePlay}>{running ? 'PAUSE' : 'PLAY'}</button></div></div><div className="preset-panel"><div className="section-label"><span>06 / SELECT OPERATION</span><span>DOES NOT CHANGE TAPE</span></div><div className="preset-list">{presets.map((item, index) => <button className={`preset ${item.id === preset.id ? 'selected' : ''}`} key={item.id} onClick={() => choosePreset(item)}><span className="preset-number">0{index + 1}</span><span><strong>{item.name}</strong><small>{item.description}</small></span><span className="arrow">↗</span></button>)}</div></div><div className="result-card"><div className="section-label"><span>07 / RESULT</span><span>{machine.halted ? 'COMPUTED' : 'WAITING'}</span></div><p>{machine.halted ? `Tape result: ${tapeValue(machine.tape)}₂ = ${tapeNumber(machine.tape)}₁₀ = ${tapeNumber(machine.tape).toString(8)}₈` : '先確認輸入，再按 PLAY。'}</p><div><button onClick={() => { reset(); setRunning(true) }}>RUN AGAIN</button><button onClick={() => document.querySelector('.tape-panel')?.scrollIntoView({ behavior: 'smooth' })}>EDIT TAPE</button></div></div></section>
    <section className="lower-grid"><div className="rules-panel"><details open><summary className="section-label"><span>08 / ADVANCED DETAILS · TRANSITION TABLE</span><span>δ(Q, Σ) → (Q′, Σ′, D)</span></summary><div className="table-wrap"><table><thead><tr><th>FROM</th><th>READ</th><th>WRITE</th><th>MOVE</th><th>TO</th></tr></thead><tbody>{preset.transitions.map((rule, index) => <tr className={activeRule === rule ? 'fired' : ''} key={`${rule.from}-${rule.read}-${index}`}><td>{rule.from}</td><td>{symbolLabel(rule.read)}</td><td>{symbolLabel(rule.write)}</td><td>{directionLabel(rule.direction)}</td><td>{rule.to}</td></tr>)}</tbody></table></div></details></div></section>
    <footer><span>PIANO TURING MACHINE / 2026</span><span>{preset.musicalNote}</span><span>AN INSTRUMENT FOR THINKING</span></footer>
  </main>
}
export default App
